INSERT INTO CATEGORIA (DESCRICAO) VALUES ('TODOS');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('BOLSAS');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('CALÇADOS');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('MASCULINO');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('FEMININO');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('UNISEX');


INSERT INTO PRODUTO (NOME, URL, PRECO, DESCONTO) VALUES ('CASACO', 'https://cea.vtexassets.com/arquivos/ids/9261147/Casaco-Feminino-Longo-Com-Bolsos-Kaki-9359741-Kaki_1.jpg?v=636924261557930000', 99.90, NULL);
INSERT INTO PRODUTO (NOME, URL, PRECO, DESCONTO) VALUES ('TENIS', 'https://static.dafiti.com.br/p/Nike-T%C3%AAnis-Nike-Wmns-Revolution-5-Preto-0154-6507015-1-zoom.jpg', 199.90, 30);
INSERT INTO PRODUTO (NOME, URL, PRECO, DESCONTO) VALUES ('BLUSA REGATA', 'https://img.lojasrenner.com.br/item/545071061/zoom/1.jpg', 30, 10);
INSERT INTO PRODUTO (NOME, URL, PRECO, DESCONTO) VALUES ('BLUSA', 'https://cea.vtexassets.com/arquivos/ids/14581098/Blusa-Feminina-Basica-Manga-Curta-Decote-Redondo-Preta-9941597-Preto_1.jpg?v=637281825119200000', 199.90, 30);

INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (1, 4);
INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (1, 5);
INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (1, 6);

INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (2, 4);

INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (3, 4);
INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (4, 5);


INSERT INTO ROLE (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE (NAME) VALUES ('ROLE_CLIENTE');