INSERT INTO CATEGORIA (DESCRICAO) VALUES ('TODOS');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('BOLSAS');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('CALÇADOS');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('MASCULINO');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('FEMININO');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('UNISEX');


INSERT INTO PRODUTO (NOME, URL, PRECO, DESCONTO) VALUES ('CASACO', 'TESTE.COM.BR/CASACO', 99.90, NULL);
INSERT INTO PRODUTO (NOME, URL, PRECO, DESCONTO) VALUES ('TENIS', 'TESTE.COM.BR/TENIS', 199.90, 30);
INSERT INTO PRODUTO (NOME, URL, PRECO, DESCONTO) VALUES ('BLUSA REGATA', 'TESTE.COM.BR/REGATA', 30, 10);
INSERT INTO PRODUTO (NOME, URL, PRECO, DESCONTO) VALUES ('BLUSA', 'TESTE.COM.BR/BLUSA', 199.90, 30);

INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (1, 4);
INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (1, 5);
INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (1, 6);

INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (2, 4);

INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (3, 4);
INSERT INTO PRODUTO_CATEGORIAS (PRODUTO_ID, CATEGORIA_ID) VALUES (4, 5);


INSERT INTO ROLE (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE (NAME) VALUES ('ROLE_CLIENTE');