openapi: 3.0.2
info:
  title: camelo--banckend
  version: 1.0.0
paths:
  /produtos/promocao:
    get:
      responses:
        '200':
          $ref: '#/components/responses/ProdutosEmPromocao'
        '400':
          $ref: '#/components/responses/InfoErro'
        '404':
          $ref: '#/components/responses/InfoErro'
        '500':
          $ref: '#/components/responses/InfoErro'
components:
  schemas:
    Produto:
      title: Root Type for Produto
      description: ''
      type: object
      properties:
        id:
          format: int32
          type: integer
        nome:
          type: string
        url:
          type: string
        preco:
          format: double
          type: number
        desconto:
          format: int32
          type: integer
      example:
        id: 1
        nome: casaco
        url: casaco.com
        preco: 99.99
        desconto: 20
    Error:
      title: Root Type for Error
      description: ''
      type: object
      properties:
        mensagem:
          type: string
      example:
        mensagem: error
  responses:
    ProdutosEmPromocao:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Produto'
          examples:
            Produtos em promocao:
              value:
                -
                  id: 5
                  nome: some text
                  url: some text
                  preco: 14.14
                  desconto: 28
                -
                  id: 28
                  nome: some text
                  url: some text
                  preco: 76.43
                  desconto: 65
      description: Produtos em promoção
    InfoErro:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            Erro:
              value:
                mensagem: some text
      description: ''
